// <auto-generated />
using GeolocationApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeolocationApi.Migrations
{
    [DbContext(typeof(GeolocationDbContext))]
    [Migration("20220702055550_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("GeolocationApi.Data.Entities.Geolocation", b =>
                {
                    b.Property<string>("Ip")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Ip");

                    b.ToTable("Geolocations");
                });
#pragma warning restore 612, 618
        }
    }
}
